version: '3'

services:
     minio:
          container_name: "minio"
          image: minio/minio
          # restart: always
          environment:
               - MINIO_ENDPOINT=9000
               - MINIO_ROOT_USER=minio_access_key
               - MINIO_ROOT_PASSWORD=minio_secret_key
          ports:
               - 9000:9000
               - 9090:9090
          volumes:
               - ./data/:/data
          command: server /data --console-address ":9090"
          expose:
             - 9000

